"""Add discovered_services and service_health tables

Revision ID: 613e3cd31034
Revises: f4ec68247c38
Create Date: 2026-07-02 00:35:58.857230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '613e3cd31034'
down_revision: Union[str, Sequence[str], None] = 'f4ec68247c38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discovered_services',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('service_id', sa.String(length=128), nullable=False),
    sa.Column('service_name', sa.String(length=128), nullable=False),
    sa.Column('service_type', sa.String(length=128), nullable=False),
    sa.Column('endpoints', sa.JSON(), nullable=True),
    sa.Column('host', sa.String(length=128), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('health_check_url', sa.String(length=512), nullable=True),
    sa.Column('health_status', sa.String(length=32), nullable=True),
    sa.Column('discovery_source', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('discovered_services', schema=None) as batch_op:
        batch_op.create_index('idx_service_name_host', ['service_name', 'host'], unique=False)
        batch_op.create_index(batch_op.f('ix_discovered_services_service_id'), ['service_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_discovered_services_service_name'), ['service_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_discovered_services_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('telemetry_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_telemetry_events_uncorrelated'), ['uncorrelated'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('telemetry_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_telemetry_events_uncorrelated'))

    with op.batch_alter_table('discovered_services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discovered_services_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_discovered_services_service_name'))
        batch_op.drop_index(batch_op.f('ix_discovered_services_service_id'))
        batch_op.drop_index('idx_service_name_host')

    op.drop_table('discovered_services')
    # ### end Alembic commands ###
