"""Add runbooks table

Revision ID: 8cea4b9cd539
Revises: bbf0f9c594d2
Create Date: 2026-06-26 15:06:06.062896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cea4b9cd539'
down_revision: Union[str, Sequence[str], None] = 'bbf0f9c594d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runbooks',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('service_name', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.String(length=2048), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_runbooks_tenant_service', 'runbooks', ['tenant_id', 'service_name'], unique=False)
    op.create_index(op.f('ix_runbooks_created_at'), 'runbooks', ['created_at'], unique=False)
    op.create_index(op.f('ix_runbooks_service_name'), 'runbooks', ['service_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_runbooks_service_name'), table_name='runbooks')
    op.drop_index(op.f('ix_runbooks_created_at'), table_name='runbooks')
    op.drop_index('idx_runbooks_tenant_service', table_name='runbooks')
    op.drop_table('runbooks')
    # ### end Alembic commands ###
